### PR TITLE
Update pulumi-master to v1.48.0 of upstream

### PR DESCRIPTION
**Pull request by jen20**
This pull request updates `pulumi-master` with the commits in v1.48.0 of the upstream Terraform provider.

### CODE REVIEW

**Comment by lukehoban** [comment]
We no longer use the `Gopkg.*` files from this repo - right? @pgavlin 

If true, should we just remove them instead of continuing to try to keep them up to date?

**Review by lukehoban — APPROVED** [review]
LGTM

We no longer use the Gopkg.* files from this repo - right? @pgavlin

If true, should we just remove them instead of continuing to try to keep them up to date?

**Comment by pgavlin** [comment]
> We no longer use the Gopkg.* files from this repo - right? @pgavlin
> 
> If true, should we just remove them instead of continuing to try to keep them up to date?

Correct :)

**Comment by jen20** [comment]
I don't think we use them, since we're using `govendor-override` in `pulumi-aws`. I'm happy to remove them instead.

**Review by pgavlin — APPROVED** [review]

**Comment by jen20** [comment]
I'll open a new pull request for updating this without touching the upstream vendor, and removing `Gopkg.{lock,toml}`.

**Pull request closed without merging**
